/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bradley;

/**
 *
 * @author AzegeleBradley
 */
import java.awt.print.PrinterException;
import java.sql.*;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

public class ProjectWork extends javax.swing.JFrame {

    /**
     * Creates new form ProjectWork
     */
    Connection cn;
    PreparedStatement pst;
    ResultSet rs;
    
    public ProjectWork() {
        initComponents();
        myconnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        submitdata = new javax.swing.JButton();
        FirstName = new javax.swing.JTextField();
        LastName = new javax.swing.JTextField();
        Gender = new javax.swing.JTextField();
        IdNumber = new javax.swing.JTextField();
        Fees = new javax.swing.JTextField();
        firstrecord = new javax.swing.JButton();
        lastrecord = new javax.swing.JButton();
        nextrecord = new javax.swing.JButton();
        previousrecord = new javax.swing.JButton();
        displayallrecords = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mytable = new javax.swing.JTable();
        tableview = new javax.swing.JButton();
        print = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mfile = new javax.swing.JMenu();
        mcreaterecord = new javax.swing.JMenuItem();
        mnavigate = new javax.swing.JMenu();
        mnextrecord = new javax.swing.JMenuItem();
        mpreviousrecord = new javax.swing.JMenuItem();
        mview = new javax.swing.JMenu();
        mfirstrecord = new javax.swing.JMenuItem();
        mlastrecord = new javax.swing.JMenuItem();
        mdisplay = new javax.swing.JMenu();
        mallrecords = new javax.swing.JMenuItem();
        mtableview = new javax.swing.JMenu();
        mshowtablerecords = new javax.swing.JMenuItem();
        mprint = new javax.swing.JMenu();
        mprintrecords = new javax.swing.JMenuItem();
        mexit = new javax.swing.JMenu();
        mclosewindow = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Student Information");

        jLabel2.setText("First Name");

        jLabel3.setText("Last Name");

        jLabel4.setText("Gender");

        jLabel5.setText("ID Number");

        jLabel6.setText("Fees");

        submitdata.setText("Submit Data");
        submitdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitdataActionPerformed(evt);
            }
        });

        firstrecord.setText("FirstRecord");
        firstrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstrecordActionPerformed(evt);
            }
        });

        lastrecord.setText("LastRecord");
        lastrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastrecordActionPerformed(evt);
            }
        });

        nextrecord.setText("NextRecord");
        nextrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextrecordActionPerformed(evt);
            }
        });

        previousrecord.setText("PreviousRecord");
        previousrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousrecordActionPerformed(evt);
            }
        });

        displayallrecords.setText("DisplayAllRecords");
        displayallrecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayallrecordsActionPerformed(evt);
            }
        });

        mytable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FirstName", "LastName", "Gender", "IdNumber", "Fees"
            }
        ));
        mytable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mytableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(mytable);

        tableview.setText("TableView");
        tableview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableviewActionPerformed(evt);
            }
        });

        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        mfile.setText("File");

        mcreaterecord.setText("Create Record");
        mcreaterecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcreaterecordActionPerformed(evt);
            }
        });
        mfile.add(mcreaterecord);

        jMenuBar1.add(mfile);

        mnavigate.setText("Navigate");

        mnextrecord.setText("NextRecord");
        mnextrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnextrecordActionPerformed(evt);
            }
        });
        mnavigate.add(mnextrecord);

        mpreviousrecord.setText("PreviousRecord");
        mpreviousrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpreviousrecordActionPerformed(evt);
            }
        });
        mnavigate.add(mpreviousrecord);

        jMenuBar1.add(mnavigate);

        mview.setText("View");

        mfirstrecord.setText("FirstRecord");
        mfirstrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mfirstrecordActionPerformed(evt);
            }
        });
        mview.add(mfirstrecord);

        mlastrecord.setText("Last Record");
        mlastrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mlastrecordActionPerformed(evt);
            }
        });
        mview.add(mlastrecord);

        jMenuBar1.add(mview);

        mdisplay.setText("Display");

        mallrecords.setText("All Records");
        mallrecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mallrecordsActionPerformed(evt);
            }
        });
        mdisplay.add(mallrecords);

        jMenuBar1.add(mdisplay);

        mtableview.setText("Table View");

        mshowtablerecords.setText("ShowTableRecords");
        mshowtablerecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mshowtablerecordsActionPerformed(evt);
            }
        });
        mtableview.add(mshowtablerecords);

        jMenuBar1.add(mtableview);

        mprint.setText("Print");

        mprintrecords.setText("Print Records");
        mprintrecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mprintrecordsActionPerformed(evt);
            }
        });
        mprint.add(mprintrecords);

        jMenuBar1.add(mprint);

        mexit.setText("Exit");

        mclosewindow.setText("CloseWindow ");
        mclosewindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mclosewindowActionPerformed(evt);
            }
        });
        mexit.add(mclosewindow);

        jMenuBar1.add(mexit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(submitdata))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(FirstName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LastName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(Gender, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IdNumber, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Fees, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nextrecord)
                            .addComponent(tableview))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(previousrecord)
                                    .addComponent(firstrecord))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastrecord)
                                    .addComponent(displayallrecords)))
                            .addComponent(print))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(IdNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Fees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitdata)
                    .addComponent(firstrecord)
                    .addComponent(lastrecord))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextrecord)
                    .addComponent(previousrecord)
                    .addComponent(displayallrecords))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tableview)
                    .addComponent(print))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitdataActionPerformed
        // TODO add your handling code here:
        submitrecord();
    }//GEN-LAST:event_submitdataActionPerformed

    private void firstrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstrecordActionPerformed
        // TODO add your handling code here:
        getfirstrecord();
    }//GEN-LAST:event_firstrecordActionPerformed

    private void lastrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastrecordActionPerformed
        // TODO add your handling code here:
        getlastrecord();
    }//GEN-LAST:event_lastrecordActionPerformed

    private void nextrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextrecordActionPerformed
        // TODO add your handling code here:
        getnextrecord();
    }//GEN-LAST:event_nextrecordActionPerformed

    private void previousrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousrecordActionPerformed
        // TODO add your handling code here:
        getpreviousrecord();
    }//GEN-LAST:event_previousrecordActionPerformed

    private void displayallrecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayallrecordsActionPerformed
        // TODO add your handling code here:
        getallrecords();
    }//GEN-LAST:event_displayallrecordsActionPerformed

    private void tableviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableviewActionPerformed
        // TODO add your handling code here:
        gettabledetails();
    }//GEN-LAST:event_tableviewActionPerformed

    private void mytableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mytableMouseClicked
        // TODO add your handling code here:
        gettablerecord();
    }//GEN-LAST:event_mytableMouseClicked

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        printing();
    }//GEN-LAST:event_printActionPerformed

    private void mfirstrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mfirstrecordActionPerformed
        // TODO add your handling code here:
        getfirstrecord();
    }//GEN-LAST:event_mfirstrecordActionPerformed

    private void mallrecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mallrecordsActionPerformed
        // TODO add your handling code here:
        getallrecords();
    }//GEN-LAST:event_mallrecordsActionPerformed

    private void mnextrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnextrecordActionPerformed
        // TODO add your handling code here:
        getnextrecord();
    }//GEN-LAST:event_mnextrecordActionPerformed

    private void mpreviousrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpreviousrecordActionPerformed
        // TODO add your handling code here:
        getpreviousrecord();
    }//GEN-LAST:event_mpreviousrecordActionPerformed

    private void mlastrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mlastrecordActionPerformed
        // TODO add your handling code here:
        getlastrecord();
    }//GEN-LAST:event_mlastrecordActionPerformed

    private void mprintrecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mprintrecordsActionPerformed
        // TODO add your handling code here:
        printing();
    }//GEN-LAST:event_mprintrecordsActionPerformed

    private void mcreaterecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcreaterecordActionPerformed
        // TODO add your handling code here:
        submitrecord();
    }//GEN-LAST:event_mcreaterecordActionPerformed

    private void mclosewindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mclosewindowActionPerformed
        // TODO add your handling code here:
        closewindow();
    }//GEN-LAST:event_mclosewindowActionPerformed

    private void mshowtablerecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mshowtablerecordsActionPerformed
        // TODO add your handling code here:
        gettabledetails();
    }//GEN-LAST:event_mshowtablerecordsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectWork().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Fees;
    private javax.swing.JTextField FirstName;
    private javax.swing.JTextField Gender;
    private javax.swing.JTextField IdNumber;
    private javax.swing.JTextField LastName;
    private javax.swing.JButton displayallrecords;
    private javax.swing.JButton firstrecord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lastrecord;
    private javax.swing.JMenuItem mallrecords;
    private javax.swing.JMenuItem mclosewindow;
    private javax.swing.JMenuItem mcreaterecord;
    private javax.swing.JMenu mdisplay;
    private javax.swing.JMenu mexit;
    private javax.swing.JMenu mfile;
    private javax.swing.JMenuItem mfirstrecord;
    private javax.swing.JMenuItem mlastrecord;
    private javax.swing.JMenu mnavigate;
    private javax.swing.JMenuItem mnextrecord;
    private javax.swing.JMenuItem mpreviousrecord;
    private javax.swing.JMenu mprint;
    private javax.swing.JMenuItem mprintrecords;
    private javax.swing.JMenuItem mshowtablerecords;
    private javax.swing.JMenu mtableview;
    private javax.swing.JMenu mview;
    private javax.swing.JTable mytable;
    private javax.swing.JButton nextrecord;
    private javax.swing.JButton previousrecord;
    private javax.swing.JButton print;
    private javax.swing.JButton submitdata;
    private javax.swing.JButton tableview;
    // End of variables declaration//GEN-END:variables

    private void myconnection() {
    try{
        cn = DriverManager.getConnection("jdbc:mysql://localhost/studentdb","root",null);
        JOptionPane.showMessageDialog(null, "Successfully connected");
        pst=cn.prepareStatement("Select  * from studentinfo",ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
        rs=pst.executeQuery();
    }catch(Exception e){
        e.printStackTrace();
    }
    }
    private void submitrecord(){
        try{
        pst=cn.prepareStatement("insert into studentinfo values (?,?,?,?,?)");
        pst.setString(1,FirstName.getText());
        pst.setString(2,LastName.getText());
        pst.setString(3,Gender.getText());
        pst.setString(4,IdNumber.getText());
        pst.setString(5,Fees.getText());
        pst.execute();
        clear();
        JOptionPane.showMessageDialog(null,"Record Successfully Saved");
        }catch(SQLException ex){
            System.out.println(ex);
        }
    }
    public void clear(){
    FirstName.setText(null);
    LastName.setText(null);
    Gender.setText(null);
    IdNumber.setText(null);
    Fees.setText(null);
    }

    private void getfirstrecord() {
       try{
        rs.first();
        FirstName.setText(rs.getString(1));
        LastName.setText(rs.getString(2));
        Gender.setText(rs.getString(3));
        IdNumber.setText(rs.getString(4));
        Fees.setText(rs.getString(5));
        }catch(SQLException ex){
               System.out.print(ex);
               }
    }

    private void getlastrecord() {
        try{
            rs.last();
            FirstName.setText(rs.getString(1));
            LastName.setText(rs.getString(2));
            Gender.setText(rs.getString(3));
            IdNumber.setText(rs.getString(4));
            Fees.setText(rs.getString(5));
        }catch(SQLException ex){
               System.out.print(ex);
               }
    }

    private void getnextrecord() {
        try{
            if(rs.next()==true){
            FirstName.setText(rs.getString(1));
            LastName.setText(rs.getString(2));
            Gender.setText(rs.getString(3));
            IdNumber.setText(rs.getString(4));
            Fees.setText(rs.getString(5));
            }else rs.beforeFirst();
        }catch(SQLException ex){
               System.out.print(ex);
               }
    }

    private void getallrecords() {
        try{
            myconnection();
            while(rs.next()){
            System.out.println(rs.getString(1)+"\t"+
                    rs.getString(2)+"\t"+
                    rs.getString(3)+"\t"+
                    rs.getString(4)+"\t"+
                    rs.getString(5));
            }
        }catch(SQLException ex){
               System.out.print(ex);
               }
    }

    private void getpreviousrecord() {
        try{
            if(rs.previous()==true){
            FirstName.setText(rs.getString(1));
            LastName.setText(rs.getString(2));
            Gender.setText(rs.getString(3));
            IdNumber.setText(rs.getString(4));
            Fees.setText(rs.getString(5));
            }else rs.afterLast();
        }catch(SQLException ex){
               System.out.print(ex);
               }
    }
    private void gettabledetails(){
     try{
        DefaultTableModel model = (DefaultTableModel) mytable.getModel();
        myconnection();
        while(rs.next()){
            Object mydata[]={rs.getString(1),
                             rs.getString(2),
                             rs.getString(3),
                             rs.getString(4),
                             rs.getString(5)};
            model.addRow(mydata);}
     }catch(SQLException ex){
               System.out.print(ex);
               }
    }

    private void gettablerecord() {
       
            DefaultTableModel model = (DefaultTableModel) mytable.getModel();
            int nrow = mytable.getSelectedRow();
            FirstName.setText((String)model.getValueAt(nrow, 0));
            LastName.setText((String)model.getValueAt(nrow, 1));
            Gender.setText((String)model.getValueAt(nrow, 2));
            IdNumber.setText((String)model.getValueAt(nrow, 3));
            Fees.setText((String) mytable.getModel().getValueAt(nrow, 4));
        
    }

    private void printing() {
        gettabledetails();
        try {
            gettabledetails();
            mytable.print();
        } catch (PrinterException ex) {
            System.out.print(ex);
        }
        
    }

    private void closewindow() {
        JOptionPane.showMessageDialog(null,"Thank You Very Much!! \n Wish "
                + "to ServeYou Next Time. \n Bye for now");
        System.exit(0);
    }
}
